### ISSUE TITLE
Latest version of `wes-service` doesn't install

### ISSUE THREAD

**Issue by w-gao** [common-workflow-language/workflow-service#127]
We were trying to use the WES client in Toil but couldn't get version 3.3 to install (see https://github.com/DataBiosphere/toil/pull/4052#discussion_r833542155). When running `pip install wes-service` with Python 3.8, it goes into an infinite loop with the following error message:

```
Collecting ruamel.yaml<=0.15.77,>=0.12.4
  Using cached ruamel.yaml-0.15.77.tar.gz (312 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/wlgao/venv/toil_env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/0t/322xl0gx0zj0bbqq46p3fwp40000gn/T/pip-install-5dulfm8i/ruamel-yaml_f066f798e7d540fe9a54ea93917184b0/setup.py'"'"'; __file__='"'"'/private/var/folders/0t/322xl0gx0zj0bbqq46p3fwp40000gn/T/pip-install-5dulfm8i/ruamel-yaml_f066f798e7d540fe9a54ea93917184b0/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/0t/322xl0gx0zj0bbqq46p3fwp40000gn/T/pip-pip-egg-info-zn1lia8l
         cwd: /private/var/folders/0t/322xl0gx0zj0bbqq46p3fwp40000gn/T/pip-install-5dulfm8i/ruamel-yaml_f066f798e7d540fe9a54ea93917184b0/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0t/322xl0gx0zj0bbqq46p3fwp40000gn/T/pip-install-5dulfm8i/ruamel-yaml_f066f798e7d540fe9a54ea93917184b0/setup.py", line 211, in <module>
        pkg_data = _package_data(__file__.replace('setup.py', '__init__.py'))
      File "/private/var/folders/0t/322xl0gx0zj0bbqq46p3fwp40000gn/T/pip-install-5dulfm8i/ruamel-yaml_f066f798e7d540fe9a54ea93917184b0/setup.py", line 184, in _package_data
        data = literal_eval("".join(lines))
      File "/private/var/folders/0t/322xl0gx0zj0bbqq46p3fwp40000gn/T/pip-install-5dulfm8i/ruamel-yaml_f066f798e7d540fe9a54ea93917184b0/setup.py", line 156, in literal_eval
        return _convert(node_or_string)
      File "/private/var/folders/0t/322xl0gx0zj0bbqq46p3fwp40000gn/T/pip-install-5dulfm8i/ruamel-yaml_f066f798e7d540fe9a54ea93917184b0/setup.py", line 95, in _convert
        if isinstance(node, Str):
    NameError: name 'Str' is not defined
    ----------------------------------------
```

**Comment by mr-c** [comment]
@w-gao What is your `pip` version? With `pip` version 21.1.1 it eventually succeeds with `ruamel-yaml` version `0.15.42` for me.

**Comment by mr-c** [comment]
@w-gao `wes-service` 4.0 has been released, let me know if you still have issues.

**Comment by w-gao** [comment]
Thank you, @mr-c! 4.0 installs perfectly. I also realized that 3.3 eventually succeeds with `ruamel-yaml` version `0.15.42` for me as well - I just didn't wait long enough.
