### ISSUE TITLE
Running wes-server without parameters fails

### ISSUE THREAD

**Issue by dpfoose** [common-workflow-language/workflow-service#3]
Running `wes-server` without specifying any options results in a crash.
This occurs in both python 2.7 and python 3.5
```
Traceback (most recent call last):
  File "/usr/local/bin/wes-server", line 11, in <module>
    load_entry_point('wes-service==2.1', 'console_scripts', 'wes-server')()
  File "build/bdist.linux-x86_64/egg/wes_service/__init__.py", line 25, in main
  File "build/bdist.linux-x86_64/egg/wes_service/cwl_runner.py", line 173, in create_backend
  File "build/bdist.linux-x86_64/egg/wes_service/util.py", line 13, in __init__
TypeError: 'NoneType' object is not iterable
```

**Comment by goja288** [comment]
Same here linux and mac

Traceback (most recent call last):
  File "/usr/local/bin/wes-server", line 11, in <module>
    load_entry_point('wes-service==2.1', 'console_scripts', 'wes-server')()
  File "build/bdist.macosx-10.13-intel/egg/wes_service/__init__.py", line 25, in main
  File "build/bdist.macosx-10.13-intel/egg/wes_service/cwl_runner.py", line 173, in create_backend
  File "build/bdist.macosx-10.13-intel/egg/wes_service/util.py", line 13, in __init__
TypeError: 'NoneType' object is not iterable

**Comment by david4096** [comment]
Thanks this was helpful! As a workaround any option will pass!

`wes-server --opt a=b`
