### ISSUE TITLE
Job fails for WDL with Toil backend

### ISSUE THREAD

**Issue by jaeddy** [common-workflow-language/workflow-service#59]
When running the `md5sum.wdl` workflow using Toil, the job never leaves the "QUEUED" state. After attempting to retrieve the run log, a 500 error is returned.

Note: this occurred after installing from `master`, not my fork/branch used in #57.

```
$ wes-client --host=localhost:8080 --proto=http --attachments="testdata/md5sum.input" testdata/md5sum.wdl testdata/md5sum.wdl.json
INFO:root:Workflow run id is 1939085ec06e4629b931ec76fa3f9805
```
At this point, the run shows up as "QUEUED" in the server console output (see below), but never changes state.

(eventually had to keyboard interrupt out of this step...)

```
$ wes-client --host=localhost:8080 --proto=http --get 1939085ec06e4629b931ec76fa3f9805
ERROR:root:{u'status': 500, u'type': u'about:blank', u'detail': u'The server encountered an internal error and was unable to complete your request.  Either the server is overloaded or there is an error in the application.', u'title': u'Internal Server Error'}
```

After attempting to view the run log, I can see that there's an error related to the WDL version of the workflow (draft-2 instead of v1.0), but I'm not sure why that would fail here and pass in integration tests.

Full console outputs from the local server:
```
INFO:werkzeug:127.0.0.1 - - [06/Sep/2018 14:13:10] "POST /ga4gh/wes/v1/runs HTTP/1.1" 200 -
Process Process-1:
Traceback (most recent call last):
  File "/Users/jaeddy/anaconda/envs/synorchestrator/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/Users/jaeddy/anaconda/envs/synorchestrator/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jaeddy/code/github/projects/workflow-service/wes_service/toil_wes.py", line 200, in run
    '"workflow_type_version" to be "v1.0": ' + str(version))
RuntimeError: workflow_type "cwl", "wdl" requires "workflow_type_version" to be "v1.0": draft-2
INFO:root:Workflow 1939085ec06e4629b931ec76fa3f9805: QUEUED
INFO:werkzeug:127.0.0.1 - - [06/Sep/2018 14:13:10] "GET /ga4gh/wes/v1/runs/1939085ec06e4629b931ec76fa3f9805/status HTTP/1.1" 200 -
INFO:root:Workflow 1939085ec06e4629b931ec76fa3f9805: QUEUED
INFO:werkzeug:127.0.0.1 - - [06/Sep/2018 14:13:18] "GET /ga4gh/wes/v1/runs/1939085ec06e4629b931ec76fa3f9805/status HTTP/1.1" 200 -
INFO:root:Workflow 1939085ec06e4629b931ec76fa3f9805: QUEUED
INFO:werkzeug:127.0.0.1 - - [06/Sep/2018 14:13:26] "GET /ga4gh/wes/v1/runs/1939085ec06e4629b931ec76fa3f9805/status HTTP/1.1" 200 -
INFO:root:Workflow 1939085ec06e4629b931ec76fa3f9805: QUEUED
ERROR:flask.app:Exception on /ga4gh/wes/v1/runs/1939085ec06e4629b931ec76fa3f9805 [GET]
Traceback (most recent call last):
  File "/Users/jaeddy/anaconda/envs/synorchestrator/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jaeddy/anaconda/envs/synorchestrator/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/jaeddy/anaconda/envs/synorchestrator/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/jaeddy/anaconda/envs/synorchestrator/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jaeddy/anaconda/envs/synorchestrator/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jaeddy/anaconda/envs/synorchestrator/lib/python2.7/site-packages/connexion/decorators/decorator.py", line 73, in wrapper
    response = function(request)
  File "/Users/jaeddy/anaconda/envs/synorchestrator/lib/python2.7/site-packages/connexion/decorators/validation.py", line 293, in wrapper
    return function(request)
  File "/Users/jaeddy/anaconda/envs/synorchestrator/lib/python2.7/site-packages/connexion/decorators/decorator.py", line 44, in wrapper
    response = function(request)
  File "/Users/jaeddy/anaconda/envs/synorchestrator/lib/python2.7/site-packages/connexion/decorators/parameter.py", line 219, in wrapper
    return function(**kwargs)
  File "/Users/jaeddy/code/github/projects/workflow-service/wes_service/toil_wes.py", line 326, in GetRunLog
    return job.getlog()
  File "/Users/jaeddy/code/github/projects/workflow-service/wes_service/toil_wes.py", line 134, in getlog
    with open(self.request_json, 'r') as f:
IOError: [Errno 2] No such file or directory: u'/Users/jaeddy/workflows/1939085ec06e4629b931ec76fa3f9805/request.json'
INFO:werkzeug:127.0.0.1 - - [06/Sep/2018 14:13:41] "GET /ga4gh/wes/v1/runs/1939085ec06e4629b931ec76fa3f9805 HTTP/1.1" 500 -
```

**Comment by DailyDreaming** [comment]
https://github.com/common-workflow-language/workflow-service/blob/b46377763d7cba0570e91770d07b10387bca7011/wes_service/toil_wes.py#L198

Should be rewritten.  ^

I'll submit a quick PR.  WDL shouldn't really have any version restrictions.
