### ISSUE TITLE
python3 support broken, no indication in readme py2 only

### ISSUE THREAD

**Issue by gijzelaerr** [common-workflow-language/workflow-service#63]
```
$   .venv/bin/wes-client --proto http --host=locahost:8080 --list
Traceback (most recent call last):
  File ".venv/bin/wes-client", line 7, in <module>
    from wes_client.wes_client_main import main
  File "/home/gijs/Work/buis/.venv/lib/python3.6/site-packages/wes_client/wes_client_main.py", line 11, in <module>
    from wes_client.util import modify_jsonyaml_paths, WESClient
  File "/home/gijs/Work/buis/.venv/lib/python3.6/site-packages/wes_client/util.py", line 12, in <module>
    from urllib import urlopen
ImportError: cannot import name 'urlopen'
```

**Comment by tetron** [comment]
Sorry about that, we need to put some tests in place to cover multiple Python versions (or maybe go Python 3 only)

**Comment by gijzelaerr** [comment]
PR accepted
